"Settings" {
    // Set to 1 for live, or 0 for test
    "live"                  "0"

    // Test Settings
    "SERVER_ADDRESS_TEST"   "192.184.89.215"
    "SERVER_PORT_TEST"      "80"
    "SERVER_HOST_TEST"      "ash47.net"
    "SERVER_PATH_TEST"      "/test.php"

    // Live Settings
    "SERVER_ADDRESS_LIVE"   "192.184.89.215"
    "SERVER_PORT_LIVE"      "80"
    "SERVER_HOST_LIVE"      "ash47.net"
    "SERVER_PATH_LIVE"      "/test.php"
}