"StatInfo"
{

    "modID"             "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    "schemaID"          "XXXXXXXXXXXXXXXX"

    -- Do we need to enable the round API or not.
    "HAS_ROUNDS"        "true"

    -- Do we want statCollection to use team winner for game victory?
    "GAME_WINNER"       "true"

    -- Do we want statCollection to use ancient explosions for game victory?
    "ANCIENT_EXPLOSION" "true"

}
